name: Deploy

on:
  push:
    branches: [miguel]
  pull_request:
    branches: [miguel]

jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout Repositort
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Fresh npm install
        run: npm ci

      - name: Run Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}